name: Test Formalities

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Test Formalities
    uses: georgesapkin/openwrt-actions-shared-workflows/.github/workflows/formal.yml@formal-check-for-more-guideline-violations
